/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as SiteCompatibilityRouteImport } from './routes/_site/compatibility'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteStudioRouteImport } from './routes/_site/studio'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBookRouteImport } from './routes/app/book'
import { Route as AppBuildRouteImport } from './routes/app/build'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppQuotesRouteImport } from './routes/app/quotes'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffBookingsRouteImport } from './routes/staff/bookings'
import { Route as StaffCatalogRouteImport } from './routes/staff/catalog'
import { Route as StaffJobsRouteImport } from './routes/staff/jobs'
import { Route as StaffQuotesRouteImport } from './routes/staff/quotes'
import { Route as StaffBrandsRouteImport } from './routes/staff/brands'
import { Route as StaffTeamRouteImport } from './routes/staff/team'
import { Route as SiteAuIndexRouteImport } from './routes/_site/au/index'
import { Route as SiteAuCityRouteImport } from './routes/_site/au/$city'
import { Route as SiteBuildsIndexRouteImport } from './routes/_site/builds/index'
import { Route as SiteBuildsSlugRouteImport } from './routes/_site/builds/$slug'
import { Route as SiteGuidesIndexRouteImport } from './routes/_site/guides/index'
import { Route as SiteGuidesSlugRouteImport } from './routes/_site/guides/$slug'
import { Route as SiteShopIndexRouteImport } from './routes/_site/shop/index'
import { Route as SiteShopSkuRouteImport } from './routes/_site/shop/$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteCompatibilityRoute = SiteCompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStudioRoute = SiteStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBuildRoute = AppBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRouteRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffBookingsRoute = StaffBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCatalogRoute = StaffCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffJobsRoute = StaffJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffQuotesRoute = StaffQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffTeamRoute = StaffTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffBrandsRoute = StaffBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => StaffRouteRoute,
} as any)
const SiteAuIndexRoute = SiteAuIndexRouteImport.update({
  id: '/au/',
  path: '/au/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuCityRoute = SiteAuCityRouteImport.update({
  id: '/au/$city',
  path: '/au/$city',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBuildsIndexRoute = SiteBuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBuildsSlugRoute = SiteBuildsSlugRouteImport.update({
  id: '/builds/$slug',
  path: '/builds/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGuidesIndexRoute = SiteGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGuidesSlugRoute = SiteGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopIndexRoute = SiteShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopSkuRoute = SiteShopSkuRouteImport.update({
  id: '/shop/$sku',
  path: '/shop/$sku',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/compatibility': typeof SiteCompatibilityRoute
  '/contact': typeof SiteContactRoute
  '/privacy': typeof SitePrivacyRoute
  '/studio': typeof SiteStudioRoute
  '/terms': typeof SiteTermsRoute
  '/app/book': typeof AppBookRoute
  '/app/build': typeof AppBuildRoute
  '/app/chat': typeof AppChatRoute
  '/app/quotes': typeof AppQuotesRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/catalog': typeof StaffCatalogRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/staff/team': typeof StaffTeamRoute
  '/staff/brands': typeof StaffBrandsRoute
  '/app/': typeof AppIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/au/$city': typeof SiteAuCityRoute
  '/builds/$slug': typeof SiteBuildsSlugRoute
  '/guides/$slug': typeof SiteGuidesSlugRoute
  '/shop/$sku': typeof SiteShopSkuRoute
  '/au/': typeof SiteAuIndexRoute
  '/builds/': typeof SiteBuildsIndexRoute
  '/guides/': typeof SiteGuidesIndexRoute
  '/shop/': typeof SiteShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/compatibility': typeof SiteCompatibilityRoute
  '/contact': typeof SiteContactRoute
  '/privacy': typeof SitePrivacyRoute
  '/studio': typeof SiteStudioRoute
  '/terms': typeof SiteTermsRoute
  '/app/book': typeof AppBookRoute
  '/app/build': typeof AppBuildRoute
  '/app/chat': typeof AppChatRoute
  '/app/quotes': typeof AppQuotesRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/catalog': typeof StaffCatalogRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/staff/team': typeof StaffTeamRoute
  '/staff/brands': typeof StaffBrandsRoute
  '/app': typeof AppIndexRoute
  '/staff': typeof StaffIndexRoute
  '/au/$city': typeof SiteAuCityRoute
  '/builds/$slug': typeof SiteBuildsSlugRoute
  '/guides/$slug': typeof SiteGuidesSlugRoute
  '/shop/$sku': typeof SiteShopSkuRoute
  '/au': typeof SiteAuIndexRoute
  '/builds': typeof SiteBuildsIndexRoute
  '/guides': typeof SiteGuidesIndexRoute
  '/shop': typeof SiteShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/_site/compatibility': typeof SiteCompatibilityRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/studio': typeof SiteStudioRoute
  '/_site/terms': typeof SiteTermsRoute
  '/app/book': typeof AppBookRoute
  '/app/build': typeof AppBuildRoute
  '/app/chat': typeof AppChatRoute
  '/app/quotes': typeof AppQuotesRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/catalog': typeof StaffCatalogRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/staff/team': typeof StaffTeamRoute
  '/staff/brands': typeof StaffBrandsRoute
  '/app/': typeof AppIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/_site/au/$city': typeof SiteAuCityRoute
  '/_site/builds/$slug': typeof SiteBuildsSlugRoute
  '/_site/guides/$slug': typeof SiteGuidesSlugRoute
  '/_site/shop/$sku': typeof SiteShopSkuRoute
  '/_site/au/': typeof SiteAuIndexRoute
  '/_site/builds/': typeof SiteBuildsIndexRoute
  '/_site/guides/': typeof SiteGuidesIndexRoute
  '/_site/shop/': typeof SiteShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/staff'
    | '/login'
    | '/compatibility'
    | '/contact'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/app/book'
    | '/app/build'
    | '/app/chat'
    | '/app/quotes'
    | '/staff/bookings'
    | '/staff/catalog'
    | '/staff/jobs'
    | '/staff/quotes'
    | '/staff/team'
    | '/staff/brands'
    | '/app/'
    | '/staff/'
    | '/au/$city'
    | '/builds/$slug'
    | '/guides/$slug'
    | '/shop/$sku'
    | '/au/'
    | '/builds/'
    | '/guides/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/compatibility'
    | '/contact'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/app/book'
    | '/app/build'
    | '/app/chat'
    | '/app/quotes'
    | '/staff/bookings'
    | '/staff/catalog'
    | '/staff/jobs'
    | '/staff/quotes'
    | '/staff/team'
    | '/staff/brands'
    | '/app'
    | '/staff'
    | '/au/$city'
    | '/builds/$slug'
    | '/guides/$slug'
    | '/shop/$sku'
    | '/au'
    | '/builds'
    | '/guides'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/staff'
    | '/_site'
    | '/login'
    | '/_site/compatibility'
    | '/_site/contact'
    | '/_site/privacy'
    | '/_site/studio'
    | '/_site/terms'
    | '/app/book'
    | '/app/build'
    | '/app/chat'
    | '/app/quotes'
    | '/staff/bookings'
    | '/staff/catalog'
    | '/staff/jobs'
    | '/staff/quotes'
    | '/staff/team'
    | '/staff/brands'
    | '/app/'
    | '/staff/'
    | '/_site/au/$city'
    | '/_site/builds/$slug'
    | '/_site/guides/$slug'
    | '/_site/shop/$sku'
    | '/_site/au/'
    | '/_site/builds/'
    | '/_site/guides/'
    | '/_site/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/compatibility': {
      id: '/_site/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof SiteCompatibilityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/studio': {
      id: '/_site/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof SiteStudioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/build': {
      id: '/app/build'
      path: '/build'
      fullPath: '/app/build'
      preLoaderRoute: typeof AppBuildRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/quotes': {
      id: '/app/quotes'
      path: '/quotes'
      fullPath: '/app/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/bookings': {
      id: '/staff/bookings'
      path: '/bookings'
      fullPath: '/staff/bookings'
      preLoaderRoute: typeof StaffBookingsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/catalog': {
      id: '/staff/catalog'
      path: '/catalog'
      fullPath: '/staff/catalog'
      preLoaderRoute: typeof StaffCatalogRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/jobs': {
      id: '/staff/jobs'
      path: '/jobs'
      fullPath: '/staff/jobs'
      preLoaderRoute: typeof StaffJobsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/quotes': {
      id: '/staff/quotes'
      path: '/quotes'
      fullPath: '/staff/quotes'
      preLoaderRoute: typeof StaffQuotesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/team': {
      id: '/staff/team'
      path: '/team'
      fullPath: '/staff/team'
      preLoaderRoute: typeof StaffTeamRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/brands': {
      id: '/staff/brands'
      path: '/brands'
      fullPath: '/staff/brands'
      preLoaderRoute: typeof StaffBrandsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_site/au/': {
      id: '/_site/au/'
      path: '/au'
      fullPath: '/au/'
      preLoaderRoute: typeof SiteAuIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/au/$city': {
      id: '/_site/au/$city'
      path: '/au/$city'
      fullPath: '/au/$city'
      preLoaderRoute: typeof SiteAuCityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/builds/': {
      id: '/_site/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof SiteBuildsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/builds/$slug': {
      id: '/_site/builds/$slug'
      path: '/builds/$slug'
      fullPath: '/builds/$slug'
      preLoaderRoute: typeof SiteBuildsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/guides/': {
      id: '/_site/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof SiteGuidesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/guides/$slug': {
      id: '/_site/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof SiteGuidesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop/': {
      id: '/_site/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof SiteShopIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop/$sku': {
      id: '/_site/shop/$sku'
      path: '/shop/$sku'
      fullPath: '/shop/$sku'
      preLoaderRoute: typeof SiteShopSkuRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBookRoute: typeof AppBookRoute
  AppBuildRoute: typeof AppBuildRoute
  AppChatRoute: typeof AppChatRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBookRoute: AppBookRoute,
  AppBuildRoute: AppBuildRoute,
  AppChatRoute: AppChatRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffBookingsRoute: typeof StaffBookingsRoute
  StaffCatalogRoute: typeof StaffCatalogRoute
  StaffJobsRoute: typeof StaffJobsRoute
  StaffQuotesRoute: typeof StaffQuotesRoute
  StaffTeamRoute: typeof StaffTeamRoute
  StaffBrandsRoute: typeof StaffBrandsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffBookingsRoute: StaffBookingsRoute,
  StaffCatalogRoute: StaffCatalogRoute,
  StaffJobsRoute: StaffJobsRoute,
  StaffQuotesRoute: StaffQuotesRoute,
  StaffTeamRoute: StaffTeamRoute,
  StaffBrandsRoute: StaffBrandsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteCompatibilityRoute: typeof SiteCompatibilityRoute
  SiteContactRoute: typeof SiteContactRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteStudioRoute: typeof SiteStudioRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteAuCityRoute: typeof SiteAuCityRoute
  SiteBuildsSlugRoute: typeof SiteBuildsSlugRoute
  SiteGuidesSlugRoute: typeof SiteGuidesSlugRoute
  SiteShopSkuRoute: typeof SiteShopSkuRoute
  SiteAuIndexRoute: typeof SiteAuIndexRoute
  SiteBuildsIndexRoute: typeof SiteBuildsIndexRoute
  SiteGuidesIndexRoute: typeof SiteGuidesIndexRoute
  SiteShopIndexRoute: typeof SiteShopIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCompatibilityRoute: SiteCompatibilityRoute,
  SiteContactRoute: SiteContactRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteStudioRoute: SiteStudioRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteAuCityRoute: SiteAuCityRoute,
  SiteBuildsSlugRoute: SiteBuildsSlugRoute,
  SiteGuidesSlugRoute: SiteGuidesSlugRoute,
  SiteShopSkuRoute: SiteShopSkuRoute,
  SiteAuIndexRoute: SiteAuIndexRoute,
  SiteBuildsIndexRoute: SiteBuildsIndexRoute,
  SiteGuidesIndexRoute: SiteGuidesIndexRoute,
  SiteShopIndexRoute: SiteShopIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
